SPORTS = {
'baseball': 'baseball',
'mbball': 'men\'s basketball',
'mcross': 'men\'s cross country',
'football': 'football',
'mgolf': 'men\'s golf',
'mgym': 'men\'s gymnastic',
'mten': 'men\'s tennis',
'mtrack': 'men\'s track and field',
'wrestling': 'wrestling',
'wbball': 'women\'s basketball',
'wcross': 'women\'s cross country',
'wgolf': 'women\'s golf',
'wgym': 'women\'s gymnastic',
'wsoc': 'soccer',
'softball': 'softball',
'wswim': 'swimming and diving',
'wten': 'women\'s tennis',
'wtrack': 'women\'s track and field',
'wvball': 'volleyball'
}

sports_list = [
'baseball',
'men\'s basketball',
'men\'s cross country',
'football',
'men\'s golf',
'men\'s gymnastic',
'men\'s tennis',
'men\'s track and field',
'wrestling',
'women\'s basketball',
'women\'s cross country',
'women\'s golf',
'women\'s gymnastic',
'soccer',
'softball',
'swimming and diving',
'women\'s tennis',
'women\'s track and field',
'volleyball'
]
